WolframResearch/WAS-Kubernetes

EnvironmentSetup/AWS/README.md
EnvironmentSetup/Azure/README.md

This PR improves the setup instructions for AWS and Azure. Also minors a missing slash in the license deployment.

Improve Setup Instructions

---

EnvironmentSetup/AWS/Source/deployments/active-web-elements-server-deployment.yaml
EnvironmentSetup/AWS/Source/deployments/endpoint-manager-deployment.yaml
EnvironmentSetup/AWS/Source/deployments/resource-manager-deployment.yaml
EnvironmentSetup/AWS/Source/setup
EnvironmentSetup/Azure/Source/deployments/active-web-elements-server-deployment.yaml
EnvironmentSetup/Azure/Source/deployments/endpoint-manager-deployment.yaml
EnvironmentSetup/Azure/Source/deployments/resource-manager-deployment.yaml
EnvironmentSetup/Azure/Source/setup

Added changes for 1.0.1 minor version release.

minor version release 1.0.1

---

EnvironmentSetup/AWS/Source/kafka/kafka-persistent.yaml
EnvironmentSetup/Azure/Source/kafka/kafka-persistent.yaml

This PR removes the redundant kafka probes.

Remove redundant kafka proves

---

README.md

Necessary to use the client service commands

adding documenation for loading the WAS client package 

---

EnvironmentSetup/AWS/Source/deployments/active-web-elements-server-deployment.yaml
EnvironmentSetup/AWS/Source/deployments/endpoint-manager-deployment.yaml
EnvironmentSetup/AWS/Source/deployments/resource-manager-deployment.yaml
EnvironmentSetup/AWS/Source/setup
EnvironmentSetup/Azure/Source/deployments/active-web-elements-server-deployment.yaml
EnvironmentSetup/Azure/Source/deployments/endpoint-manager-deployment.yaml
EnvironmentSetup/Azure/Source/deployments/resource-manager-deployment.yaml
EnvironmentSetup/Azure/Source/setup

increase version number to 1.1.3

increase version number to 1.1.3

---

EnvironmentSetup/AWS/README.md
EnvironmentSetup/AWS/Source/Dockerfile
EnvironmentSetup/AWS/Source/cluster-autoscaler/cluster-autoscaler-autodiscover.yaml
EnvironmentSetup/AWS/Source/deployments/active-web-elements-server-deployment.yaml
EnvironmentSetup/AWS/Source/hpa/active-web-elements-server-hpa-autoscaler.yaml
EnvironmentSetup/AWS/Source/ingress-controller/deploy.yaml
EnvironmentSetup/AWS/Source/metrics-server/metrics-server-deployment.yaml
EnvironmentSetup/AWS/Source/setup
EnvironmentSetup/AWS/Source/terraform/main.tf
EnvironmentSetup/AWS/Source/terraform/variables.tf

* Upgraded ingress-controller **0.4.5** -> **1.2.1**
* Updated metrics-server/metrics-server-deployment
beta.kubernetes.io/os -> **kubernetes.io/os**
* Upgraded terraform 0.14 -> **1.2.4**
* Upgraded hashicorp/aws 3.0 -> **3.75.2**
* Upgraded terraform-aws-modules/vpc/aws 2.66.0 -> **3.14.2**
* Upgraded terraform-aws-modules/eks/aws 13.2.1 -> **16.1.0**
* Upgraded kubernetes cluster version 1.20 -> **1.22**
(AWS EKS supports cluster version <= v1.22 https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html)
* Upgraded aws cli 1.XX -> **2.XX**
* Update setup script
* Updated README.md

[WAS-495] - WAS AWS script upgrade

---

EnvironmentSetup/Azure/README.md
EnvironmentSetup/Azure/Source/Dockerfile
EnvironmentSetup/Azure/Source/deployments/active-web-elements-server-deployment.yaml
EnvironmentSetup/Azure/Source/hpa/active-web-elements-server-hpa-autoscaler.yaml
EnvironmentSetup/Azure/Source/ingress-controller/deploy.yml
EnvironmentSetup/Azure/Source/ingress/was-ingress-awes-service.yml
EnvironmentSetup/Azure/Source/ingress/was-ingress-endpoint-manager-service.yml
EnvironmentSetup/Azure/Source/ingress/was-ingress-nodefiles-service.yml
EnvironmentSetup/Azure/Source/ingress/was-ingress-resources-manager-service.yml
EnvironmentSetup/Azure/Source/metrics-server/metrics-server-deployment.yaml
EnvironmentSetup/Azure/Source/setup
EnvironmentSetup/Azure/Source/terraform/main.tf
EnvironmentSetup/Azure/Source/terraform/variables.tf

* Upgraded ingress-controller 0.4.5 -> 1.2.1
* Updated metrics-server/metrics-server-deployment
* beta.kubernetes.io/os -> kubernetes.io/os
* Upgraded terraform 0.14 -> 1.2.4
* Upgraded hashicorp/azurerm 2.0 -> 3.75.2
* Upgraded kubernetes cluster version 1.20 -> 1.22
(Azure AKS supports cluster version up to v1.24(preview)
https://docs.microsoft.com/en-us/azure/aks/supported-kubernetes-versions?tabs=azure-cli)
* Added ingressClassName in ingresses
* Upgraded aws cli 1.XX -> 2.XX
* Updated setup script
* Updated README.md
* Updated application-server version

[WAS-496] - WAS Azure script upgrade

---

EnvironmentSetup/AWS/Source/ingress/was-ingress-awes-service.yml
EnvironmentSetup/Azure/Source/ingress/was-ingress-awes-service.yml

Reference: https://github.com/kubernetes/ingress-nginx/blob/nginx-0.12.0/docs/user-guide/annotations.md

modified ingress-nginx default timeout

---

EnvironmentSetup/Azure/README.md
EnvironmentSetup/Azure/Source/setup
EnvironmentSetup/Azure/Source/terraform/main.tf

I updated the setup script. Previously we were storing the WAS details on local files. I added an Azure Blob to store values for --delete operation.
* Added an Azure Blob under the was-creds-rg-$PARSED_TENANT resource group to store credentials
It stores
```
GET_CLUSTER_NAME
GET_REGION
GET_SAN
ACCOUNT_KEY
MINIO_ACCESS_KEY
MINIO_SECRET_KEY
TENANT_ID
TF_RESOURCE_GROUP_NAME
RESOURCE_GROUP_NAME
AD_APP_ID
AD_APP_PASSWORD
AZURE_DOMAIN
STORAGE_CONTAINER_NAME
RESOURCE_INFO_BUCKET
NODE_FILES_BUCKET
CREDS_RG_NAME
CREDS_STORAGE_ACCOUNT_NAME
CREDS_STORAGE_CONTAINER_NAME
BASE_URL
RESOURCE_MANAGER_URL
ENDPOINT_MANAGER_URL
NODEFILES_URL
ENDPOINTS_INFO_URL
RESTART_URL
```
values
* Added an option for the script as --get-creds to check the current values.
* Formatted script file.
* Updated comments.

[WAS-519] - Updated Azure setup script

---

EnvironmentSetup/AWS/Source/deployments/active-web-elements-server-deployment.yaml
EnvironmentSetup/AWS/Source/setup
EnvironmentSetup/Azure/Source/deployments/active-web-elements-server-deployment.yaml
EnvironmentSetup/Azure/Source/setup

This PR has bug fixes for the kernel timeout issue.

Release 3.1.4

---

EnvironmentSetup/AWS/Source/deployments/active-web-elements-server-deployment.yaml
EnvironmentSetup/AWS/Source/deployments/endpoint-manager-deployment.yaml
EnvironmentSetup/AWS/Source/deployments/resource-manager-deployment.yaml
EnvironmentSetup/Azure/Source/deployments/active-web-elements-server-deployment.yaml
EnvironmentSetup/Azure/Source/deployments/endpoint-manager-deployment.yaml
EnvironmentSetup/Azure/Source/deployments/resource-manager-deployment.yaml

This PR has changes to support Prometheus metrics.

Release version 3.1.5

---

EnvironmentSetup/AWS/Source/deployments/active-web-elements-server-deployment.yaml
EnvironmentSetup/Azure/Source/deployments/active-web-elements-server-deployment.yaml

This Release has WebEngine 13.2 update.

WAS Release 3.2

---

EnvironmentSetup/AWS/Source/hpa/active-web-elements-server-hpa-autoscaler.yaml
EnvironmentSetup/AWS/Source/hpa/endpoint-manager-hpa-autoscaler.yaml
EnvironmentSetup/AWS/Source/hpa/minio-hpa-autoscaler.yaml
EnvironmentSetup/AWS/Source/hpa/resource-manager-hpa-autoscaler.yaml
EnvironmentSetup/AWS/Source/setup
EnvironmentSetup/AWS/Source/terraform/variables.tf

I applied updates for upgrading 1.22 to 1.23.
Reference: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.23.md#changelog-since-v1220
* Updated some of the fields in setup script
* Updated HorizontalPodAutoscaler api version(`autoscaling/v2beta2` to `autoscaling/v2`)
* Upgraded cluster version `1.22` to `1.23`

[WAS-524] Upgraded EKS kubernetes version to 1.23

---

EnvironmentSetup/Azure/Source/Dockerfile
EnvironmentSetup/Azure/Source/hpa/active-web-elements-server-hpa-autoscaler.yaml
EnvironmentSetup/Azure/Source/hpa/endpoint-manager-hpa-autoscaler.yaml
EnvironmentSetup/Azure/Source/hpa/minio-hpa-autoscaler.yaml
EnvironmentSetup/Azure/Source/hpa/resource-manager-hpa-autoscaler.yaml
EnvironmentSetup/Azure/Source/setup
EnvironmentSetup/Azure/Source/terraform/variables.tf

* Updated Dockerfile
* Updated API versions
* Updated cluster-version to 1.24

[WAS-525] Upgraded AKS kubernetes version to 1.24

---

EnvironmentSetup/AWS/Source/deployments/active-web-elements-server-deployment.yaml
EnvironmentSetup/AWS/Source/setup
EnvironmentSetup/Azure/Source/deployments/active-web-elements-server-deployment.yaml
EnvironmentSetup/Azure/Source/setup

Changing the minor version number or this release as it has a Kubernetes version upgrade

Release 3.3

---

EnvironmentSetup/AWS/Source/deployments/active-web-elements-server-deployment.yaml
EnvironmentSetup/AWS/Source/setup
EnvironmentSetup/Azure/Source/deployments/active-web-elements-server-deployment.yaml
EnvironmentSetup/Azure/Source/setup

Patch version release with small bug fixes. [WAs-551]

Release 3.3.1

---

.github/workflows/master.yml
EnvironmentSetup/Azure/Source/ingress-controller/deploy.yml

* Created GitHub action to validate terraform, kubernetes manifests and docker images.
* Fixed Azure/Source/ingress-controller/deploy.yml::ConfigMap
```
EnvironmentSetup/Azure/Source/ingress-controller/deploy.yml - ConfigMap ingress-nginx-controller failed validation: error unmarshalling resource: error converting YAML to JSON: yaml: unmarshal errors:
line 15: key "data" already set in map
```
* Tested in a private repository
edit: it created a workflow under Actions tab.

[WAS-585] - GitHub Actions validate configuration files

---

EnvironmentSetup/Azure/README.md
EnvironmentSetup/Azure/Source/Dockerfile
EnvironmentSetup/Azure/Source/setup
EnvironmentSetup/Azure/Source/terraform/variables.tf

* Updated Dockerfile
* Updated variables.tf
* Updated setup function
* No YAML file changes needed.

[WAS-606] - Azure Kubernetes version is upgraded to 1.27

---

EnvironmentSetup/AWS/Source/deployments/active-web-elements-server-deployment.yaml
EnvironmentSetup/AWS/Source/deployments/endpoint-manager-deployment.yaml
EnvironmentSetup/AWS/Source/deployments/resource-manager-deployment.yaml
EnvironmentSetup/AWS/Source/setup
EnvironmentSetup/Azure/Source/deployments/active-web-elements-server-deployment.yaml
EnvironmentSetup/Azure/Source/deployments/endpoint-manager-deployment.yaml
EnvironmentSetup/Azure/Source/deployments/resource-manager-deployment.yaml
EnvironmentSetup/Azure/Source/setup

* Upgraded Wolfram Engine version from 13.2.0 to 14.0.0
* Upgraded resource manager version from 1.2.2 to 1.2.6
* Upgraded endpoint manager version from 1.2.1 to 1.2.5

Release 3.3.9

---

EnvironmentSetup/Azure/README.md
EnvironmentSetup/Azure/Source/Dockerfile
EnvironmentSetup/Azure/Source/deployments/active-web-elements-server-deployment.yaml
EnvironmentSetup/Azure/Source/deployments/endpoint-manager-deployment.yaml
EnvironmentSetup/Azure/Source/deployments/resource-manager-deployment.yaml
EnvironmentSetup/Azure/Source/ingress/was-ingress-awes-info.yaml
EnvironmentSetup/Azure/Source/kafka/kafka-persistent.yaml
EnvironmentSetup/Azure/Source/pvc/awes-pvcs.yaml
EnvironmentSetup/Azure/Source/sc/kafka-standardssd-xfs.yaml
EnvironmentSetup/Azure/Source/services/active-web-elements-server-service.yaml
EnvironmentSetup/Azure/Source/setup
EnvironmentSetup/Azure/Source/strimzi-kafka-deployment/051-PriorityLevelConfig-operator.yaml
EnvironmentSetup/Azure/Source/strimzi-kafka-deployment/052-FlowSchema-operator.yaml
EnvironmentSetup/Azure/Source/strimzi-kafka-deployment/060-Deployment-strimzi-cluster-operator.yaml
EnvironmentSetup/Azure/Source/terraform/main.tf
EnvironmentSetup/Azure/Source/terraform/outputs.tf
EnvironmentSetup/Azure/Source/terraform/variables.tf

* Cluster k8s version upgraded from v1.27 to v1.33.
* Added storageClass for strimzi-kafka.
* Updated README.md file.
* Revised Dockerfile.
* Tested & passed WAS test suite.
* endpoint-manager: 1.2.5 -> 1.2.8
* resource-manager: 1.2.6 -> 1.2.9

Azure - K8s version is upgraded to v.1.33
